### ISSUE TITLE
ModuleNotFoundError: No module named 'telebot'

### ISSUE THREAD

**Issue by monosans** [sudoskys/telegramify-markdown#10]
https://github.com/sudoskys/telegramify-markdown/blob/3f1eaefebff921639762ac7f2015471e1d54c7c1/src/telegramify_markdown/render.py#L7

**Comment by sudoskys** [comment]
my fault

**Comment by sudoskys** [comment]
I will maintain a beta version in the future and will not publish the new version easily.
