### ISSUE TITLE
max_line_length setting has no effect

### ISSUE THREAD

**Issue by xingty** [sudoskys/telegramify-markdown#15]
I think this is because when we import the `telegramify_markdown` module, it also imports the `render` module. As a result, max_line_length is imported and initialized. Therefore, even though we update the value of max_line_length, it will not have any effect.

My test code is the same as the example written on README.
```python
from telegramify_markdown import customize
import telegramify_markdown

customize.max_line_length = 256
customize.strict_markdown = True

md = """
[Treating Otitis Externa in Dogs | Today's Veterinary Practice](https://todaysveterinarypractice.com/dermatology/treating-otitis-externa-in-dogs/)
"""


def main():
    escaped = telegramify_markdown.convert(md)
    print(escaped)


main()
```

env:
OS: macOS
python: python3.11

**Comment by sudoskys** [comment]
This may be a design problem. I may update a major version to solve this problem using dependency injection.

**Comment by sudoskys** [comment]
```
converted = telegramify_markdown.markdownify(
    markdown_text,
    max_line_length=None,  # If you want to change the max line length for links, images, set it to the desired value.
    normalize_whitespace=False
)
print(converted)
# export Markdown to Telegram MarkdownV2 style.
```

Use telegramify_markdown.markdownify instead

**Comment by xingty** [comment]
> ```
> converted = telegramify_markdown.markdownify(
>     markdown_text,
>     max_line_length=None,  # If you want to change the max line length for links, images, set it to the desired value.
>     normalize_whitespace=False
> )
> print(converted)
> # export Markdown to Telegram MarkdownV2 style.
> ```
> 
> Use telegramify_markdown.markdownify instead

thanks a lot
