### ISSUE TITLE
Extra space added after quote character

### ISSUE THREAD

**Issue by nj-vs-vh** [sudoskys/telegramify-markdown#21]
Hi, thanks for the great library!

One small thing I bumped into is that it adds an extra space after block quote symbol (`>`):

```python
telegramify_markdown.markdownify(">quote")
# result: '> quote\n'
```

This space is actually preserved by Telegram. For larger quotes it leads to the following problem:

<img width="482" alt="image" src="https://github.com/user-attachments/assets/06a240e2-77dc-45c5-8fe9-33a79e661bc7">

**Comment by sudoskys** [comment]
Um, so you expect to align them?

**Comment by sudoskys** [comment]
I'll release a patch to fix this
