### ISSUE TITLE
Problems parsing custom emoji

### ISSUE THREAD

**Issue by tonycody** [sudoskys/telegramify-markdown#32]
```
![👍](tg://emoji?id=5368324170671202286)
```

The top of this chart is right and the bottom is wrong. The one below is after escaping
![image](https://github.com/user-attachments/assets/a775570b-6b26-4a74-8317-2b65d168d81a)

Custom emoji markdown should be sent as is and should not be escaped.

**Comment by sudoskys** [comment]
Investigating
