### ISSUE TITLE
Latex support for text, right, left commands

### ISSUE THREAD

**Issue by MNovruzov** [sudoskys/telegramify-markdown#35]
`A = X × \left( (P)/100 \right) × (V)/365`

`\text{R} = \frac{\text{EXAMPLE}}{\text{Any}}`

**Comment by sudoskys** [comment]
I think the best solution is to remove these commands. It is difficult to represent them in text.

**Comment by MNovruzov** [comment]
I think so, yes. It's hard to represent them in text, but they need to be processed.  
Otherwise, the formulas look unattractive.  
For example, commands like `\right` and `\left` can simply be skipped without replacing them with anything.  
`text` can be replaced with placeholders like `IT` or `TT`, depending on your preference.

**Comment by sudoskys** [comment]
I have released a new version to fix this issue, if this is not fixed please comment
