### ISSUE TITLE
bug related to ```

### ISSUE THREAD

**Issue by jocker916** [sudoskys/telegramify-markdown#38]
Hello,

Is it possible to add escaping for the  ```  character within the code? Otherwise, a bug occurs, and the formatting breaks. Additionally, since Telegram has a 4096-character limit and I send messages in two parts when this limit is exceeded, could the library include a feature to automatically split the text while preserving the formatting?
sample code:

```python3
print("```")
```

Thank you.

**Comment by sudoskys** [comment]
![18](https://github.com/user-attachments/assets/bbb3274c-c08a-47a9-a64d-e211e4153cdb)
![45](https://github.com/user-attachments/assets/261c347a-49ad-41da-bcd2-567004f973cf)

I don't see any issues happening, can you give me more information?

**Comment by sudoskys** [comment]
Since our splitting is done by another library, and in order not to destroy the simplicity of this library (not to introduce more complex modules or cause disaster), I think you can write a helper function yourself, splitting by newline and calculating the message.

**Comment by theurs** [comment]
> Since our splitting is done by another library, and in order not to destroy the simplicity of this library (not to introduce more complex modules or cause disaster), I think you can write a helper function yourself, splitting by newline and calculating the message.

Is this a private library? It's difficult to write my own function, if you just cut by the new line, the tags of the code blocks will break. And other large blocks, especially nested ones.

**Comment by sudoskys** [comment]
we use https://github.com/miyuchina/mistletoe parse markdown text

**Comment by theurs** [comment]
What do you use to cut a block of code that is more than 4k characters?

**Comment by sudoskys** [comment]
I posted to https://telegra.ph/api

**Comment by sudoskys** [comment]
> What do you use to cut a block of code that is more than 4k characters?

https://github.com/eternnoir/pyTelegramBotAPI/blob/master/telebot/util.py#L330

**Comment by theurs** [comment]
> > What do you use to cut a block of code that is more than 4k characters?
> 
> https://github.com/eternnoir/pyTelegramBotAPI/blob/master/telebot/util.py#L330

It doesn't support markdown.

**Comment by theurs** [comment]
```python
from typing import List, Optional, Tuple
import re

def chunk_markdown(text: str, max_chunk_size: int = 3000) -> List[str]:
    """
    Split markdown text into chunks of specified maximum size while preserving code blocks.
    
    Args:
        text: Input markdown text
        max_chunk_size: Maximum allowed size of each chunk
        
    Returns:
        List of markdown text chunks
    """
    chunks: List[str] = []
    current_chunk: List[str] = []
    current_size: int = 0
    in_code_block: bool = False
    code_block_header: Optional[str] = None
    pending_code_block_end: bool = False
    
    # Split text into lines while preserving empty lines
    lines: List[str] = text.splitlines(keepends=True)
    
    def add_chunk() -> None:
        """Helper function to add accumulated lines as a new chunk."""
        nonlocal current_size
        if current_chunk:
            chunks.append(''.join(current_chunk))
            current_chunk.clear()
            current_size = 0
    
    def is_code_block_start(line: str) -> Tuple[bool, Optional[str]]:
        """
        Check if line is a code block start and extract its header.
        
        Returns:
            Tuple of (is_start: bool, header: Optional[str])
        """
        stripped = line.lstrip()
        if stripped.startswith('```'):
            return True, line.rstrip()
        return False, None
    
    def is_code_block_end(line: str) -> bool:
        """Check if line is a code block end."""
        return line.lstrip().startswith('```') and not line.lstrip()[3:].strip()
    
    for i, line in enumerate(lines):
        line_size = len(line)
        next_line = lines[i + 1] if i + 1 < len(lines) else None
        
        # Handle code block boundaries
        if not in_code_block:
            is_start, header = is_code_block_start(line)
            if is_start:
                in_code_block = True
                code_block_header = header
                pending_code_block_end = False
        else:
            if is_code_block_end(line):
                in_code_block = False
                code_block_header = None
                pending_code_block_end = False
        
        # Start new chunk if current would exceed max size
        if current_size + line_size > max_chunk_size and current_chunk:
            if in_code_block and not pending_code_block_end:
                current_chunk.append('```\n')  # Close code block in current chunk
                pending_code_block_end = True
            add_chunk()
            if in_code_block and code_block_header:
                current_chunk.append(f'{code_block_header}\n')  # Reopen code block in new chunk
                pending_code_block_end = False
            current_size = line_size
        else:
            current_size += line_size
        
        # Skip adding closing tag if it's already pending
        if pending_code_block_end and is_code_block_end(line):
            continue
            
        current_chunk.append(line)
    
    # Add final chunk
    add_chunk()
    
    return chunks
```

**Comment by sudoskys** [comment]
Maybe we can implement a tokenizer internally. I'll look into how to split the parser blocks.

**Comment by sudoskys** [comment]
This problem has been completely solved: https://github.com/sudoskys/telegramify-markdown/blob/pypi_0.2.0/playground/telegramify_case.py
