### ISSUE TITLE
Avoid synchronous IO for rendering Mermaid diagrams

### ISSUE THREAD

**Issue by monosans** [sudoskys/telegramify-markdown#47]
Hi! Thanks a lot for this incredible project. I am absolutely amazed by the new `telegramify` function.

Recently Mermaid rendering was added, and I noticed that it does synchronous IO with `requests`, which is very bad for users who develop asynchronous bots with `aiogram` for example.

To fix this, I have a few suggestions:

- Allow disabling Mermaid rendering,  `render_mermaid=False`. I think this one is necessary.
- Instead of downloading the image, pass https url to telegram, as it will download the image itself.
- Add support for asynchronous http with aiohttp. Maybe under specific extra: `pip install telegramify-markdown[async]`. I don't think this is needed, if the second suggestion will be implemented.

**Comment by sudoskys** [comment]
We will configure a dedicated configuration class for `telegramify`.

Regarding the asynchronous issue, I actually intend to fully implement it as asynchronous. However, this might lead to compatibility problems, so perhaps I should write a `telegramify_async` method.

```python
import asyncio

async def telegramify_async(message):
    """Asynchronous method"""
    await asyncio.sleep(0.1)
    return f"Telegram [Async]: {message}"

def sync_adapter(coroutine):
    """
    Synchronous adapter: Executes a coroutine and explicitly starts an event loop
    in a synchronous context.
    """
    try:
        loop = asyncio.get_event_loop()
    except RuntimeError:  # If no event loop is running, create a new one
        loop = asyncio.new_event_loop()
        asyncio.set_event_loop(loop)

    if not loop.is_running():
        return loop.run_until_complete(coroutine)  # Run the coroutine until it completes
    else:
        raise RuntimeError("Attempting to call an asynchronous function synchronously inside an active event loop")

def telegramify(message):
    """
    Provides support for synchronous calls (adapts asynchronous methods through the adapter)
    """
    return sync_adapter(telegramify_async(message))
```

what you think?

**Comment by sudoskys** [comment]
It seems that the synchronous methods of telegramify can be completely removed and converted to asynchronous methods. . .

I will complete this conversion in a while

**Comment by sudoskys** [comment]
To ensure compatibility, I will add a period of time to determine whether the synchronous method is compatible within the asynchronous loop and display a warning.

**Comment by sudoskys** [comment]
I have released a new version to fix this issue.
